<a href="https://colab.research.google.com/github/allsyaa/SIC-Semesta-2026/blob/main/HandsOn_Lists_Dictionaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 🐍 Hands-On: Lists & Dictionaries
### Sesi 7 — Python untuk Pemula

Selamat datang di sesi hands-on! Notebook ini adalah teman praktik dari materi slide **"Lists & Dictionaries"**.

Di notebook ini kamu akan **mempraktikkan langsung** semua materi yang sudah dipelajari:

1. 📋 **List** — menyimpan banyak data berurutan
2. 📖 **Dictionary** — menyimpan data berpasangan (key → value)
3. 🔒 **Tuple** *(bonus)* — List yang datanya terkunci
4. 🎯 **Set** *(bonus)* — kumpulan data unik
5. 🔢 **NumPy Array** *(bonus)* — array untuk komputasi numerik
6. 🧮 **NumPy Aljabar Linear** *(bonus)* — operasi matriks

Di akhir notebook ada **Tugas Mandiri** yang harus kamu kerjakan sendiri untuk melatih pemahamanmu. Selamat belajar! 🚀

---

> 💡 **Cara pakai notebook ini:**
> - Jalankan setiap sel kode dengan menekan `Shift + Enter`.
> - Jangan hanya membaca — **ketik ulang** dan coba ubah-ubah kodenya sendiri!
> - Kerjakan sel dengan tanda **✏️ Coba Sendiri** sebelum lanjut ke bagian berikutnya.
> - Jangan takut error! Error adalah bagian dari proses belajar coding.

---
# 📋 Bagian 1: List

## 1.1 Kenapa Kita Butuh List?

Bayangkan kita harus menyimpan nama 5 siswa. Cara yang merepotkan adalah membuat 5 variabel terpisah seperti di bawah ini.

In [1]:
# Cara lama yang merepotkan
nama1 = "Ana"
nama2 = "Budi"
nama3 = "Cici"
nama4 = "Dedi"
nama5 = "Eni"

print(nama1, nama2, nama3, nama4, nama5)
# Coba bayangkan kalau siswanya ada 100 orang, apakah ini praktis?

Ana Budi Cici Dedi Eni


Dengan **List**, kita cukup pakai **satu variabel** untuk menyimpan semua data itu sekaligus.

In [2]:
# Cara yang lebih baik: pakai List
nama = ["Ana", "Budi", "Cici", "Dedi", "Eni"]
print(nama)
print(type(nama))

['Ana', 'Budi', 'Cici', 'Dedi', 'Eni']
<class 'list'>


## 1.2 Apa itu List?

**List** adalah wadah berurutan yang bisa menyimpan banyak item dalam satu variabel. Ciri-cirinya:

- Ditulis dengan kurung siku `[ ]`
- Urutan item **selalu diingat**
- Item boleh sama, boleh berbeda tipe data
- Diakses lewat nomor **index**, dimulai dari `0`

In [3]:
buah = ["apel", "jeruk", "mangga"]

print(buah)             # menampilkan seluruh isi list
print(type(buah))       # <class 'list'>
print(len(buah))        # jumlah item di dalam list

['apel', 'jeruk', 'mangga']
<class 'list'>
3


✏️ **Coba Sendiri:** Buat list bernama `hobi` berisi 3 hobi favoritmu, lalu tampilkan dengan `print()`.

In [4]:
# Tulis kodemu di sini
hobi = ["makan", "tidur", "pecut claude"]

for i in hobi:
  print(i)

makan
tidur
pecut claude


## 1.3 Menambah & Menghapus Item

List itu fleksibel — isinya bisa berubah kapan saja dengan beberapa method berikut:

| Method | Fungsi |
|---|---|
| `.append(item)` | menambah item di **akhir** list |
| `.insert(index, item)` | menyisipkan item di **posisi tertentu** |
| `.remove(item)` | menghapus item **tertentu** (berdasarkan nilainya) |

In [5]:
nama = ["Ana", "Budi", "Cici"]

# Menambah di akhir
nama.append("Dedi")
print(nama)   # ['Ana', 'Budi', 'Cici', 'Dedi']

# Menyisipkan di posisi tertentu (index 1)
nama.insert(1, "Eni")
print(nama)   # ['Ana', 'Eni', 'Budi', 'Cici', 'Dedi']

# Menghapus item tertentu
nama.remove("Budi")
print(nama)   # ['Ana', 'Eni', 'Cici', 'Dedi']

['Ana', 'Budi', 'Cici', 'Dedi']
['Ana', 'Eni', 'Budi', 'Cici', 'Dedi']
['Ana', 'Eni', 'Cici', 'Dedi']


## 1.4 Mengurutkan List (`sort`)

In [6]:
nilai = [88, 70, 95, 60]

nilai.sort()
print(nilai)                 # [60, 70, 88, 95]

nilai.sort(reverse=True)
print(nilai)                 # [95, 88, 70, 60]

# sorted() tidak mengubah list asli, hanya membuat list baru
angka = [3, 1, 2]
angka_urut = sorted(angka)
print("asli   :", angka)
print("urutan :", angka_urut)

[60, 70, 88, 95]
[95, 88, 70, 60]
asli   : [3, 1, 2]
urutan : [1, 2, 3]


In [7]:
list_kota = ['Jakarta', 'Bandung', 'Bogor', 'Cilacap', 'Depok', 'Tasikmalaya']

In [8]:
print(list_kota.sort())

None


In [9]:
# def sort():
#   # operasi uruta

In [10]:
list_kota

['Bandung', 'Bogor', 'Cilacap', 'Depok', 'Jakarta', 'Tasikmalaya']

In [11]:
list_kota.sort(reverse=True)
list_kota

['Tasikmalaya', 'Jakarta', 'Depok', 'Cilacap', 'Bogor', 'Bandung']

✏️ **Coba Sendiri:** Dari list `hobi` yang kamu buat tadi, tambahkan 1 hobi baru dengan `.append()`, lalu urutkan list itu secara alfabetis dengan `.sort()`.

In [12]:
# Tulis kodemu di sini
hobi.append("pecut gemini")
hobi.sort()
for i in hobi:
  print(i)

makan
pecut claude
pecut gemini
tidur


## 1.5 Indexing — Mengakses Item List

Setiap item punya "alamat" berupa nomor index. Index dari depan mulai dari `0`, dan index dari belakang mulai dari `-1`.

In [13]:
nama = ["Ana", "Budi", "Cici", "Dedi", "Eni"]
#          0       1       2       3       4
#         -5      -4      -3      -2      -1

print(nama[0])     # Ana   -> item pertama
print(nama[2])     # Cici
print(nama[-1])    # Eni   -> item terakhir (dari belakang)

Ana
Cici
Eni


## 1.6 Slicing — Mengambil Sebagian List

Gunakan `[awal:akhir]` untuk mengambil beberapa item sekaligus. **Ingat**: index akhir **tidak ikut** terambil!

In [14]:
nama = ["Ana", "Budi", "Cici", "Dedi", "Eni"]

print(nama[1:3])     # ['Budi', 'Cici']       -> index 1 s.d. 2
print(nama[:2])      # ['Ana', 'Budi']        -> dari awal sampai index 1
print(nama[::2])     # ['Ana', 'Cici', 'Eni']  -> loncat 2 index sekali ambil

['Budi', 'Cici']
['Ana', 'Budi']
['Ana', 'Cici', 'Eni']


In [15]:
nama[::-2]

['Eni', 'Cici', 'Ana']

✏️ **Coba Sendiri:** Dengan list `nama` di atas, ambil 3 item terakhir menggunakan slicing (petunjuk: gunakan index negatif, misal `nama[-3:]`).

In [16]:
# Tulis kodemu di sini
print(nama[2:])
print(nama[-3:])

['Cici', 'Dedi', 'Eni']
['Cici', 'Dedi', 'Eni']


## 1.7 Iterasi List dengan Loop

Gunakan `for` untuk memproses **semua item** dalam list, satu per satu, tanpa perlu tahu jumlah itemnya.

In [17]:
nama = ["Ana", "Budi", "Cici", "Dedi"]

for item in nama:
    print("Halo,", item)

Halo, Ana
Halo, Budi
Halo, Cici
Halo, Dedi


> 💡 Loop otomatis berhenti di akhir list — cocok untuk list yang panjang atau jumlahnya belum diketahui, dibanding mengakses satu-satu pakai index.

In [18]:
numbers = [1, 2, 3, 4, 5]

# Square every number in the list
squared = list(map(lambda x: x ** 2, numbers))
squared

[1, 4, 9, 16, 25]

---
# 📖 Bagian 2: Dictionary

## 2.1 Apa itu Dictionary?

**Dictionary** menyimpan data berpasangan **key → value**, seperti kartu nama: setiap informasi (key) punya nilainya sendiri (value).

- Ditulis dengan kurung kurawal `{ }`
- Setiap pasangan ditulis `"key": value`
- **Key harus unik** (tidak boleh ada 2 key yang sama), tapi value boleh apa saja

In [19]:
profil = {
    "nama": "Budi",
    "umur": 20,
    "kota": "Jakarta"
}

print(profil)
print(type(profil))

{'nama': 'Budi', 'umur': 20, 'kota': 'Jakarta'}
<class 'dict'>


## 2.2 Mengakses Value lewat Key

Dictionary tidak diakses dengan nomor index, melainkan lewat **nama key**-nya.

In [20]:
profil = {"nama": "Budi", "umur": 20}

print(profil["nama"])          # Budi

# Cara aman, tidak error jika key tidak ada
print(profil.get("kota"))      # None (karena key "kota" belum ada)

Budi
None


In [21]:
try:
    profil["kota"]   # "kota" belum ada di profil -> akan memicu KeyError
except KeyError as e:
    print("KeyError:", e)


KeyError: 'kota'


> ⚠️ **Hati-hati:** `profil["kota"]` akan menghasilkan `KeyError` jika key `"kota"` tidak ada. Gunakan `.get()` agar lebih aman.

## 2.3 Menambah & Mengubah Dictionary

- Jika key **sudah ada** → value diperbarui
- Jika key **belum ada** → key baru langsung ditambahkan

In [22]:
profil = {"nama": "Budi", "umur": 20}

# Menambah key baru
profil["kota"] = "Jakarta"

# Mengubah value yang sudah ada
profil["umur"] = 21

print(profil)   # {'nama': 'Budi', 'umur': 21, 'kota': 'Jakarta'}

{'nama': 'Budi', 'umur': 21, 'kota': 'Jakarta'}


✏️ **Coba Sendiri:** Buat dictionary bernama `siswa` berisi `nama`, `kelas`, dan `nilai` milikmu (boleh rekaan). Lalu ubah nilai `nilai` menjadi 10 poin lebih tinggi.

In [23]:
# Tulis kodemu di sini
siswa = {"nama": "oi", "kelas": "12", "nilai": 70}
siswa["nilai"] += 10
for key, value in siswa.items():
    print(key, "→", value)

nama → oi
kelas → 12
nilai → 80


## 2.4 Iterasi Dictionary dengan Loop

Gunakan `.items()` untuk mengambil **key dan value sekaligus** di setiap perulangan.

In [24]:
profil = {"nama": "Budi", "umur": 20, "kota": "Jakarta"}

for key, value in profil.items():
    print(key, "→", value)

nama → Budi
umur → 20
kota → Jakarta


In [25]:
for key in profil.keys():
  print(key)

nama
umur
kota


In [26]:
for value in profil.values():
  print(value)

Budi
20
Jakarta


## 2.5 List vs Dictionary — Kapan Pakai yang Mana?

| | **List** | **Dictionary** |
|---|---|---|
| Akses data | lewat index angka `list[0]` | lewat key/nama `dict["kunci"]` |
| Cocok untuk | data berurutan/sejenis | data berlabel/berpasangan |
| Contoh | daftar nilai, daftar belanja | profil siswa, data kontak |
| Sintaks | `nama = [item1, item2, ...]` | `nama = {"key": value}` |

## 2.6 Bonus: Kombinasi List & Dictionary

List dan Dictionary bisa digabung — List berisi banyak Dictionary. Ini sangat umum dipakai untuk menyimpan data banyak "record", misalnya data banyak siswa sekaligus.

In [27]:
siswa = [
    {"nama": "Ana", "nilai": 90},
    {"nama": "Budi", "nilai": 85},
]

for s in siswa:
    print(s["nama"], s["nilai"])

Ana 90
Budi 85


In [28]:
siswa[0]["nama"]

'Ana'

In [29]:
profil = {
    "nama": "Adam",
    "nama_hewan_peliharaan": ["manis", "mawar"]
}
profil

{'nama': 'Adam', 'nama_hewan_peliharaan': ['manis', 'mawar']}

---
# 🔒 Bagian 3 (Bonus): Tuple

**Tuple** mirip List, tapi datanya **terkunci** — tidak bisa diubah (*immutable*) setelah dibuat.

- Ditulis dengan kurung `( )`, bukan `[ ]`
- Cocok untuk data yang **harus tetap**, misalnya koordinat `(x, y)` atau kode warna RGB

In [30]:
koordinat = (10, 20, 30)

print(koordinat[0])       # 10  -> tetap bisa diakses lewat index seperti List
print(len(koordinat))     # 3

10
3


In [31]:
# Mencoba mengubah isi tuple akan menghasilkan error
koordinat = (10, 20, 30)
try:
    koordinat[0] = 99   # ❌ baris ini yang memicu error
except TypeError as e:
    print("Error:", e)


Error: 'tuple' object does not support item assignment


> 🔎 Jalankan sel di atas — kamu akan melihat `TypeError: 'tuple' object does not support item assignment`. Itu **wajar**, karena memang itulah sifat utama Tuple: datanya tidak bisa diubah.

**List vs Tuple:**
- `List [ ]` → bisa diubah (*mutable*)
- `Tuple ( )` → tidak bisa diubah (*immutable*)

✏️ **Coba Sendiri:** Buat tuple bernama `rgb` berisi 3 angka (misalnya `(255, 0, 0)` untuk warna merah). Tampilkan item pertamanya dengan indexing.

In [32]:
# Tulis kodemu di sini
rgb = (255, 0, 0)
rgb[0]


255

---
# 🎯 Bagian 4 (Bonus): Set

**Set** menyimpan kumpulan data yang **unik** — otomatis tanpa duplikat, dan tanpa urutan yang tetap.

- Ditulis dengan kurung kurawal `{ }` (sama seperti Dictionary, tapi tanpa pasangan key-value)

In [33]:
buah = {"apel", "jeruk", "apel", "mangga", "apel"}

print(buah)   # duplikat "apel" otomatis hilang!

{'jeruk', 'mangga', 'apel'}


In [34]:
try:
    buah[0]   # Set tidak berurutan & tidak punya index, jadi ini akan error
except TypeError as e:
    print("Error:", e)


Error: 'set' object is not subscriptable


In [35]:
buah = {"apel", "jeruk", "mangga"}

buah.add("melon")        # menambah item
buah.remove("jeruk")     # menghapus item

print(buah)

{'mangga', 'melon', 'apel'}


In [36]:
list_buah = ["apel", "jeruk", "apel", "mangga",
             "apel", "jeruk", "apel", "mangga",
             "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga", "jeruk", "apel", "mangga"]
list_buah_unik = []

for buah in list_buah:
  if buah not in list_buah_unik:
    list_buah_unik.append(buah)

list_buah_unik

['apel', 'jeruk', 'mangga']

In [37]:
try:
    set(list_buah)[0]   # sama seperti sebelumnya -- Set tidak bisa diakses pakai index
except TypeError as e:
    print("Error:", e)


Error:

 'set' object is not subscriptable


In [38]:
list_buah_unik_2 = list(set(list_buah))
list_buah_unik_2

['jeruk', 'mangga', 'apel']

Set juga mendukung **operasi himpunan** matematika seperti irisan dan gabungan:

In [39]:
a = {1, 2, 3}
b = {2, 3, 4}

print(a & b)   # irisan (intersection)  -> {2, 3}
print(a | b)   # gabungan (union)       -> {1, 2, 3, 4}
print(a - b)   # selisih (difference)   -> {1}

{2, 3}
{1, 2, 3, 4}
{1}


✏️ **Coba Sendiri:** Buat sebuah List berisi angka dengan beberapa duplikat (misalnya `[1, 2, 2, 3, 3, 3]`), lalu ubah menjadi Set untuk menghilangkan duplikatnya. Petunjuk: gunakan `set(nama_list)`.

In [40]:
# Tulis kodemu di sini
angka = [1, 2, 2, 3, 3, 3]
set(angka)


{1, 2, 3}

---
# 🔢 Bagian 5 (Bonus): NumPy Array

Untuk data angka dalam jumlah besar, List biasa terasa lambat. **NumPy** adalah library Python yang menyediakan struktur data **array** yang jauh lebih cepat dan hemat memori untuk komputasi numerik.

> Jika belum terpasang, jalankan `!pip install numpy` terlebih dahulu di sel baru.

In [41]:
import numpy as np

data = np.array([10, 20, 30, 40])

print(data)            # [10 20 30 40]
print(type(data))
print(data.shape)      # (4,)  -> artinya array 1 dimensi dengan 4 elemen

[10 20 30 40]
<class 'numpy.ndarray'>
(4,)


**Kelebihan utama NumPy** dibanding List biasa: operasi matematis bisa langsung diterapkan ke **semua elemen sekaligus** (disebut *vectorized operation*), tanpa perlu loop manual.

In [42]:
data = np.array([10, 20, 30, 40])

print(data * 2)     # [20 40 60 80]   -> dikalikan 2 tanpa loop!
print(data + 5)     # [15 25 35 45]
print(data.sum())   # 100
print(data.mean())  # 25.0

# Bandingkan dengan cara List biasa (butuh loop / list comprehension):
data_list = [10, 20, 30, 40]
hasil = [x * 2 for x in data_list]
print(hasil)         # [20, 40, 60, 80]

[20 40 60 80]
[15 25 35 45]
100
25.0
[20, 40, 60, 80]


NumPy array juga bisa berbentuk **matriks (2 dimensi)**:

In [43]:
matrix = np.array([[1, 2], [3, 4]])

print(matrix)
print(matrix.shape)   # (2, 2) -> 2 baris, 2 kolom

[[1 2]
 [3 4]]
(2, 2)


✏️ **Coba Sendiri:** Buat NumPy array berisi nilai ujian `[70, 85, 90, 60, 75]`, lalu hitung rata-rata (`.mean()`), nilai tertinggi (`.max()`), dan nilai terendah (`.min()`).

In [44]:
# Tulis kodemu di sini
nilai = np.array([70, 85, 90, 60, 75])
print(nilai.mean())
print(nilai.max())
print(nilai.min())


76.0
90
60


---
# 🧮 Bagian 6 (Bonus): Operasi NumPy untuk Aljabar Linear

NumPy menyediakan operasi matriks siap pakai lewat modul `numpy.linalg`, yang menjadi dasar penting untuk *machine learning* dan *data science*.

| Operasi | Kode |
|---|---|
| Perkalian matriks | `A @ B` atau `np.dot(A, B)` |
| Transpose (baris ↔ kolom) | `A.T` |
| Determinan | `np.linalg.det(A)` |
| Invers matriks | `np.linalg.inv(A)` |

In [45]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Perkalian matriks (A @ B):")
print(A @ B) #dot product

Perkalian matriks (A @ B):
[[19 22]
 [43 50]]


In [46]:
np.cross(A, B) #cross product

/tmp/ipykernel_106/3043191085.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(A, B) #cross product


array([-4, -4])

In [47]:
print("Transpose A (A.T):")
print(A.T)

Transpose A (A.T):
[[1 3]
 [2 4]]


In [48]:
print("Determinan A:")
print(np.linalg.det(A))

Determinan A:
-2.0000000000000004


In [49]:
print("Invers matriks A:")
print(np.linalg.inv(A))

Invers matriks A:
[[-2.   1. ]
 [ 1.5 -0.5]]


✏️ **Coba Sendiri:** Buat 2 matriks 2x2 sendiri (`C` dan `D`), lalu hitung hasil perkalian matriksnya (`C @ D`) dan transpose dari `C` (`C.T`).

In [50]:
# Tulis kodemu di sini
C = np.array([[1, 2], [3, 4]])
D = np.array([[5, 6], [7, 8]])
print(C @ D)
print(C.T)


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


---
# 📝 Rangkuman

| Struktur Data | Simbol | Bisa Diubah? | Cocok Untuk |
|---|---|---|---|
| **List** | `[ ]` | ✅ Ya | Data berurutan |
| **Dictionary** | `{"key": value}` | ✅ Ya | Data berlabel (key-value) |
| **Tuple** | `( )` | ❌ Tidak | Data yang harus tetap |
| **Set** | `{item1, item2}` | ✅ Ya (isinya) | Data unik, tanpa duplikat |
| **NumPy Array** | `np.array([...])` | ✅ Ya | Komputasi numerik & matriks |

Selanjutnya, mari uji pemahamanmu lewat **Tugas Mandiri** di bawah ini!

---
# 🏠 Tugas Mandiri

Kerjakan semua soal di bawah ini **secara mandiri** (tanpa melihat jawaban dari teman). Tulis kodemu di sel kode yang sudah disediakan setelah setiap soal.

> 📌 **Aturan:**
> - Kerjakan berurutan dari soal 1 sampai selesai.
> - Gunakan `print()` untuk menampilkan setiap hasil.
> - Boleh menambahkan sel baru jika diperlukan.
> - Jika mengalami error, baca pesan errornya baik-baik — biasanya sudah memberi petunjuk letak kesalahan.

## Soal 1 — List: Daftar Belanja 🛒

Buat sebuah List bernama `belanja` berisi minimal 5 nama barang belanjaan.

1. Tampilkan seluruh isi list.
2. Tambahkan 1 barang baru menggunakan `.append()`.
3. Hapus salah satu barang menggunakan `.remove()`.
4. Urutkan list secara alfabetis dengan `.sort()`.
5. Tampilkan barang pertama dan barang terakhir menggunakan indexing.

In [51]:
# Jawaban Soal 1
belanja = ["beras", "gula", "susu", "ikan", "minyak"]
belanja.append("telur")
belanja.remove("susu")
belanja.sort()
print(belanja)
print(belanja[0])
print(belanja[-1])



['beras', 'gula', 'ikan', 'minyak', 'telur']
beras
telur


## Soal 2 — Slicing & Loop: Nilai Ujian 📊

Diberikan list nilai ujian berikut:

```python
nilai_ujian = [78, 92, 65, 88, 95, 70, 60, 85]
```

1. Tampilkan 3 nilai pertama menggunakan slicing.
2. Tampilkan 3 nilai terakhir menggunakan slicing.
3. Gunakan `for` untuk menampilkan setiap nilai beserta keterangan **"LULUS"** (jika ≥ 75) atau **"TIDAK LULUS"** (jika < 75).

In [52]:
nilai_ujian = [78, 92, 65, 88, 95, 70, 60, 85]

# Jawaban Soal 2
print(nilai_ujian[:3])
print(nilai_ujian[-3:])
for nilai in nilai_ujian:
  if nilai >= 75:
    print(nilai, "LULUS")
  else:
    print(nilai, "TIDAK LULUS")


[78, 92, 65]
[70, 60, 85]
78 LULUS
92 LULUS
65 TIDAK LULUS
88 LULUS
95 LULUS
70 TIDAK LULUS
60 TIDAK LULUS
85 LULUS


## Soal 3 — Dictionary: Kartu Profil Digital 🪪

Buat sebuah Dictionary bernama `profil_saya` berisi minimal 4 pasangan key-value tentang dirimu (contoh key: `nama`, `umur`, `hobi`, `sekolah`, `kota`).

1. Tampilkan seluruh isi dictionary.
2. Ambil salah satu value menggunakan key-nya.
3. Tambahkan 1 pasangan key-value baru.
4. Ubah salah satu value yang sudah ada.
5. Gunakan `for` dan `.items()` untuk menampilkan semua pasangan key-value dengan format:  
   `nama: Budi`

In [53]:
# Jawaban Soal 3
profil_saya = {"nama": "oi", "umur": "500", "hobi": "tidur", "kampus": "UNSIA"}

profil_saya["umur"] = 20
print("umurnya", profil_saya["umur"])

profil_saya["pacar"] = "nazwa"
for key, value in profil_saya.items():
  print(key, ":", value)

umurnya 20
nama : oi
umur : 20
hobi : tidur
kampus : UNSIA
pacar : nazwa


## Soal 4 — Kombinasi List & Dictionary: Data Nilai Kelas 🎓

Buat sebuah List bernama `kelas` berisi 3 Dictionary, di mana setiap Dictionary punya key `"nama"` dan `"nilai"` (data siswa rekaan).

1. Gunakan `for` untuk menampilkan nama dan nilai setiap siswa.
2. Hitung dan tampilkan **rata-rata nilai** seluruh siswa di kelas itu (petunjuk: kumpulkan semua nilai ke sebuah list baru, lalu gunakan `sum()` dan `len()`).

In [54]:
# Jawaban Soal 4
kelas = [{"nama": "nahda", "nilai": 50},
          {"nama": "rexxy", "nilai": 70},
          {"nama": "alini", "nilai": 30}
        ]
nila_kelas = []
for siswa in kelas:
  print(siswa["nama"], siswa["nilai"])
  nila_kelas.append(siswa["nilai"])
print(sum(nila_kelas)/len(nila_kelas))


nahda 50
rexxy 70
alini 30
50.0


## Soal 5 — Tuple: Titik Koordinat 📍

1. Buat sebuah Tuple bernama `titik_A` berisi koordinat `(x, y)` bebas, misalnya `(4, 7)`.
2. Buat juga `titik_B` dengan koordinat lain.
3. Tampilkan nilai `x` dan `y` dari masing-masing titik menggunakan indexing.
4. **Pertanyaan (jawab dengan komentar `#` di kode)**: Kenapa koordinat lebih cocok disimpan sebagai Tuple dibanding List?

In [55]:
# Jawaban Soal 5
titik_A = (1, 2)
titik_B = (3, 4)
print(titik_A[0])
print(titik_A[1])
print(titik_B[0])
print(titik_B[1])

# koordinat pakai tuple karena tuple tidak bisa diubah, dan biasanya koordinat nilainya tetap

1
2
3
4


## Soal 6 — Set: Peserta Unik 👥

Diberikan 2 List peserta webinar dari 2 sumber pendaftaran berikut (ada beberapa nama yang mendaftar dua kali):

```python
pendaftar_1 = ["Ana", "Budi", "Cici", "Dedi"]
pendaftar_2 = ["Cici", "Dedi", "Eni", "Fani"]
```

1. Ubah masing-masing List menjadi Set.
2. Tampilkan **gabungan (union)** semua peserta unik dari kedua sumber.
3. Tampilkan peserta yang **mendaftar di kedua sumber (irisan/intersection)**.
4. Tampilkan peserta yang **hanya ada di `pendaftar_1` saja (selisih/difference)**.

In [56]:
pendaftar_1 = ["Ana", "Budi", "Cici", "Dedi"]
pendaftar_2 = ["Cici", "Dedi", "Eni", "Fani"]

# Jawaban Soal 6
pendaftar_1_set = set(pendaftar_1)
pendaftar_2_set = set(pendaftar_2)
print(pendaftar_1_set.union(pendaftar_2_set))
print(pendaftar_1_set.intersection(pendaftar_2_set))
print(pendaftar_1_set.difference(pendaftar_2_set))


{'Eni', 'Ana', 'Dedi', 'Cici', 'Budi', 'Fani'}
{'Dedi', 'Cici'}
{'Ana', 'Budi'}


## Soal 7 — NumPy: Statistik Nilai Sederhana 📈

1. Buat NumPy array bernama `nilai` berisi minimal 6 angka nilai ujian bebas.
2. Tampilkan rata-rata (`.mean()`), nilai tertinggi (`.max()`), dan nilai terendah (`.min()`).
3. Buat array baru bernama `nilai_bonus` yang isinya adalah `nilai` ditambah 5 poin ke setiap elemen (tanpa loop, manfaatkan *vectorized operation*).

In [57]:
# Jawaban Soal 7
nilai = np.array([10, 20, 30, 40, 50, 60])
print(nilai.mean())
print(nilai.max())
print(nilai.min())


35.0
60
10


## Soal 8 — NumPy Aljabar Linear: Operasi Matriks 🧮 (Tantangan)

Diberikan dua matriks berikut:

```python
M1 = np.array([[2, 0], [1, 3]])
M2 = np.array([[1, 4], [2, 1]])
```

1. Hitung dan tampilkan hasil perkalian matriks `M1 @ M2`.
2. Tampilkan transpose dari `M1`.
3. Hitung determinan dari `M1`.
4. Hitung invers dari `M1`.
5. **Tantangan tambahan**: Buktikan dengan kode bahwa `M1 @ np.linalg.inv(M1)` menghasilkan matriks identitas (mendekati `[[1, 0], [0, 1]]`).

In [58]:
import numpy as np

M1 = np.array([[2, 0], [1, 3]])
M2 = np.array([[1, 4], [2, 1]])

# Jawaban Soal 8
print(M1 @ M2)
print(M1.T)
print(np.linalg.det(M1))
print(np.linalg.inv(M1))
print(M1 @ np.linalg.inv(M1))


[[2 8]
 [7 7]]
[[2 1]
 [0 3]]
6.0
[[ 0.5         0.        ]
 [-0.16666667  0.33333333]]
[[1.00000000e+00 0.00000000e+00]
 [2.77555756e-17 1.00000000e+00]]


---
## ✅ Selesai!

Kerja bagus sudah menyelesaikan seluruh materi dan tugas mandiri sesi ini! 🎉

Simpan (save) notebook ini, dan kumpulkan sesuai instruksi fasilitator kelas.

**Sampai jumpa di Sesi 8!** 👋